import { useToast } from '@/hooks/use-toast';
import config from '@/lib/config';
import { useMutation } from '@tanstack/react-query';
import ky from 'ky-universal';

export const fetchAuthHandle = async (email: string) => {
  const data = await ky
    .post(`${config.baseUrl}/auth/handle`, {
      headers: {
        'X-CSRF-TOKEN': 'qwerty',
      },
      json: {
        email,
      },
    })
    .json<AuthEmailSubmitResponse>();

  if (!data.success) throw new Error('Произошла ошибка при отправке данных');

  return data;
};

export const useAuthEmailSubmit = () => {
  return useMutation({
    mutationFn: fetchAuthHandle,
  });
};

// Generated by https://quicktype.io

export interface AuthEmailSubmitResponse {
  success: boolean;
  result: AuthEmailSubmitResponseResult;
}

export interface AuthEmailSubmitResponseResult {
  needed_authorisation: boolean;
  authorisation_data: {
    needed_password: boolean;
    needed_twofa_code: boolean;
  };
}
