import { useMutation } from '@tanstack/react-query';
import api from '@/lib/api';

export const fetchAuthHandle = async (email: string) => {
  const data = await api
    .post('auth/handle', {
      json: {
        email,
      },
    })
    .json<AuthEmailSubmitResponse>();

  if (!data.success) throw new Error('Произошла ошибка при отправке данных');

  return data;
};

export const useAuthEmailSubmit = () => {
  return useMutation({
    mutationFn: fetchAuthHandle,
  });
};

// Generated by https://quicktype.io

export interface AuthEmailSubmitResponse {
  success: boolean;
  result: AuthEmailSubmitResponseResult;
}

export interface AuthEmailSubmitResponseResult {
  needed_authorization: boolean;
  authorization_data: {
    needed_password: boolean;
    needed_twofa_code: boolean;
  };
}
